### ISSUE TITLE
void main でなくて int main を使ってください

### ISSUE THREAD

**Issue by kmyk** [niuez/Niu#13]
コンパイルが通らない https://wandbox.org/permlink/7d6KSGZCQPNlpOOF

**Comment by kmyk** [comment]
こういうコード https://judge.kimiyuki.net/submission/18 を書いて困ってたのですが、もしかして main を何も特別扱いしてないですか。それならまあ分かる

**Comment by niuez** [comment]
> もしかして main を何も特別扱いしてないですか

そうです. コンパイラ側でmainを特別扱いするようなコードは書いていません. 
C++の`int`をNiuでは使いたくないと思っているので、`int main()`を書くためには`main`に対して特別扱いするしかなさそうです.
Niu言語の`main() -> void`を, C++の`int main()`に変換するのが丸そうなので, これで解決することにします.
