### ISSUE TITLE
階乗の計算が壊れた

### ISSUE THREAD

**Issue by kmyk** [niuez/Niu#34]
v0.4.0 では動いてた (https://judge.kimiyuki.net/submission/50) はずですが、これを v0.4.1 にしたら WA になりました (https://judge.kimiyuki.net/submission/51)

**Comment by niuez** [comment]
submission/50を通した時点では`MOD 998244353`だった気がしますが、問題が`MOD 1000000007`になってます.
`1000000007`に変更するとACしました(https://judge.kimiyuki.net/submission/53)

**Comment by kmyk** [comment]
ごめんなさい :bow:
言語更新でジャッジを再起動したときに問題データが先祖返りを起こしてしまってたみたいです (998244353 に直しました)
